config/routes.rb
# == Route Map
#
#                                Prefix Verb     URI Pattern                                        Controller#Action
#                                  root GET      /                                                  home#index
#                      question_answers GET      /questions/:question_id/answers(.:format)          answers#index
#                                       POST     /questions/:question_id/answers(.:format)          answers#create
#                   new_question_answer GET      /questions/:question_id/answers/new(.:format)      answers#new
#                  edit_question_answer GET      /questions/:question_id/answers/:id/edit(.:format) answers#edit
#                       question_answer GET      /questions/:question_id/answers/:id(.:format)      answers#show
#                                       PATCH    /questions/:question_id/answers/:id(.:format)      answers#update
#                                       PUT      /questions/:question_id/answers/:id(.:format)      answers#update
#                                       DELETE   /questions/:question_id/answers/:id(.:format)      answers#destroy
#                             questions GET      /questions(.:format)                               questions#index
#                                       POST     /questions(.:format)                               questions#create
#                          new_question GET      /questions/new(.:format)                           questions#new
#                         edit_question GET      /questions/:id/edit(.:format)                      questions#edit
#                              question GET      /questions/:id(.:format)                           questions#show
#                                       PATCH    /questions/:id(.:format)                           questions#update
#                                       PUT      /questions/:id(.:format)                           questions#update
#                                       DELETE   /questions/:id(.:format)                           questions#destroy
# user_google_oauth2_omniauth_authorize GET|POST /users/auth/google_oauth2(.:format)                users/omniauth_callbacks#passthru
#  user_google_oauth2_omniauth_callback GET|POST /users/auth/google_oauth2/callback(.:format)       users/omniauth_callbacks#google_oauth2
#                      new_user_session GET      /signin(.:format)                                  home#index
#                  destroy_user_session DELETE   /signout(.:format)                                 devise/sessions#destroy
#

Rails.application.routes.draw do
  root to: "home#index"

  resources :questions do
    resources :answers
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:sessions]
  as :user do
    get 'signin', to: 'home#index', as: :new_user_session    
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[show edit update destroy]
  before_action :validate_ownership, only: [:edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    if !params[:q]
      @questions = Question.all
    else
      @questions = Question.where("title like ? or body like ?", "%#{params[:q]}%", "%#{params[:q]}%")
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit; end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:user_id, :title, :body)
  end

  def validate_ownership
    if @question.user_id != current_user.id
      flash[:notice] = "You are not authorized to perform this action"
      redirect_to questions_path
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :question_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :question_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= link_to 'Questions', questions_path %></h1>

<%= form_tag(questions_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q, params[:q]) %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.user.name %></td>
        <td><%== MarkdownFactory.instance.render(question.title) %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) if question.user_id == current_user.id %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }  if question.user_id == current_user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @question.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%== MarkdownFactory.instance.render(@question.title) %>
</p>

<p>
  <strong>Question:</strong>
  <%== MarkdownFactory.instance.render(@question.body) %>
</p>

<p>
  <strong>Answers:</strong>
  <% @question.answers.each do |answer| %>
  <p>
    <strong><%= answer.user.name %></strong>
    <p></p>
    <td><%== MarkdownFactory.instance.render(answer.body) %></td>
    <td><%= link_to 'Show', question_answer_path(@question, answer) %></td>    
  </p>
  <hr>
<% end %>
<%= link_to 'New Answer', new_question_answer_path(@question) %>
</p>

<%= link_to 'Edit', edit_question_path(@question) if @question.user_id == current_user.id %> |
<%= link_to 'Back', questions_path %>