config/routes.rb
# == Route Map
#
#                                Prefix Verb     URI Pattern                                        Controller#Action
#                                  root GET      /                                                  home#index
#                      question_answers GET      /questions/:question_id/answers(.:format)          answers#index
#                                       POST     /questions/:question_id/answers(.:format)          answers#create
#                   new_question_answer GET      /questions/:question_id/answers/new(.:format)      answers#new
#                  edit_question_answer GET      /questions/:question_id/answers/:id/edit(.:format) answers#edit
#                       question_answer GET      /questions/:question_id/answers/:id(.:format)      answers#show
#                                       PATCH    /questions/:question_id/answers/:id(.:format)      answers#update
#                                       PUT      /questions/:question_id/answers/:id(.:format)      answers#update
#                                       DELETE   /questions/:question_id/answers/:id(.:format)      answers#destroy
#                             questions GET      /questions(.:format)                               questions#index
#                                       POST     /questions(.:format)                               questions#create
#                          new_question GET      /questions/new(.:format)                           questions#new
#                         edit_question GET      /questions/:id/edit(.:format)                      questions#edit
#                              question GET      /questions/:id(.:format)                           questions#show
#                                       PATCH    /questions/:id(.:format)                           questions#update
#                                       PUT      /questions/:id(.:format)                           questions#update
#                                       DELETE   /questions/:id(.:format)                           questions#destroy
# user_google_oauth2_omniauth_authorize GET|POST /users/auth/google_oauth2(.:format)                users/omniauth_callbacks#passthru
#  user_google_oauth2_omniauth_callback GET|POST /users/auth/google_oauth2/callback(.:format)       users/omniauth_callbacks#google_oauth2
#                      new_user_session GET      /signin(.:format)                                  home#index
#                  destroy_user_session DELETE   /signout(.:format)                                 devise/sessions#destroy
#

Rails.application.routes.draw do
  root to: "home#index"

  resources :questions do
    resources :answers
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:sessions]
  as :user do
    get 'signin', to: 'home#index', as: :new_user_session    
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  question_id :integer
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_parent_question
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :validate_ownership, only: [:edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = @question.answers.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = @question.answers.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@question, @answer], notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to [@question, @answer], notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answers_url(@question), notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = @question.answers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :question_id, :body)
    end

    def validate_ownership
      if @answer.user_id != current_user.id
        flash[:notice] = "You are not authorized to perform this action"
        redirect_to questions_path
      end
    end

    def load_parent_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, url: [@question, @answer], local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', question_answer_path(@question, @answer) %> |
<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user.name %></td>
        <td><%== MarkdownFactory.instance.render(answer.question.title) %></td>        
        <td><%= link_to 'Show', question_answer_path(@question, answer) %></td>
        <td><%= link_to 'Edit', edit_question_answer_path(@question, answer)  if answer.user_id == current_user.id %></td>
        <td><%= link_to 'Destroy', [@question, answer], method: :delete, data: { confirm: 'Are you sure?' }   if answer.user_id == current_user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_question_answer_path(@question) %>
<%= link_to 'Back', question_path(@question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @answer.user.name %>
</p>

<p>
  <strong>Question:</strong>
  <%== MarkdownFactory.instance.render(@answer.question.title) %>
  <hr>
  <%== MarkdownFactory.instance.render(@answer.question.body) %>
</p>

<p>
  <strong>Answer:</strong>
  <%== MarkdownFactory.instance.render(@answer.body) %>
</p>

<%= link_to 'Edit', edit_question_answer_path(@question, @answer) if @answer.user_id == current_user.id %> |
<%= link_to 'Back', question_answers_path(@question) %>